version: "2"

volumes:
  postgresql_data_development: {}
  postgresql_backup_development: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    image: aperte_local_django
    depends_on:
      - postgresql
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.env/development/docker.postgresql.env
      - ./.env/development/django.env
    ports:
      - "8000:8000"
    command: /start

  postgresql:
    build:
      context: .
      dockerfile: ./docker/development/postgresql/Dockerfile
    image: aperte_development_postgresql
    volumes:
      - postgresql_data_development:/var/lib/postgresql/data
      - postgresql_backup_development:/backups
    env_file:
      - ./.env/development/docker.postgresql.env

  redis:
    image: redis:3.2
