#!/usr/bin/env bash


### View the available PostgreSQL backups.
###
### Usage:
###     $ docker-compose -f docker.<environment>.yml (exec |run --rm) postgresql list_backups


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


message_welcome "PostgreSQL backups that are available:"

ls -lht "${BACKUP_DIR_PATH}"
